spring: 
 datasource: 
  url: jdbc:mysql://localhost:3306/ordermyfood
  username: dbUser1
  password: Ganesha@rkd9
  
  jpa: 
   hibernate: 
    ddl-auto: update
   properties: 
    hibernate:
     dialect: org.hibernate.dialect.MySQL8InnoDBDialect 